### ISSUE TITLE
Occupancy Rendering

### ISSUE THREAD

**Issue by Zhiyuan-R** [ktertikas/part_nerf#7]
I saw in the paper your method uses occupancy-based rendering. I just wonder how the density-based method will behave. Will it be pretty bad?

**Comment by ktertikas** [comment]
Hi @Zhiyuan-VisionKing , we are using occupancy-based rendering mostly because it is easier to set the surface boundary (τ = 0.5) and to use this for the ray-part association (keep in mind that rays are only assigned to parts if at least one point along the ray has occupancy value bigger than τ). If we used density-based rendering, you would need to discover the surface threshold value!
